### PR TITLE
Convert to basic Sphinx build + GitHub Workflow

### PR DESCRIPTION
**Pull request by luator**
## Description

Get rid of the dependency on `mpi_cmake_modules` and instead convert the package to a basic Sphinx build.

Dependencies are (apart from Sphinx):
- sphinx_rtd_theme: The RTD theme
- myst_parser: For Markdown support  (though I would suggest to fully migrate to RST on the long term)

To build the documentation, simply run `make html`.

Also add GitHub Workflow which automatically builds the documentation when there is a push to `main` and deploys it (via the `gh-pages` branch) to https://intelligent-soft-robots.github.io/pam_documentation/

## How I Tested

* Build tested locally.
* GitHub Workflow is tested through this PR (see https://intelligent-soft-robots.github.io/pam_documentation/ for the result).

### CODE REVIEW

**Comment by luator** [comment]
The build documentation is now available here: https://intelligent-soft-robots.github.io/pam_documentation/

**Review by vincentberenz — APPROVED** [review]
wow, that was quick !
Thanks a lot of the update

**Comment by vincentberenz** [comment]
if I am correct: this will build everytime something is pushed to the master branch ?

**Comment by luator** [comment]
> if I am correct: this will build everytime something is pushed to the master branch ?

Exactly.

**Comment by luator** [comment]
Resolved merge conflict.

@vincentberenz Can I merge or do you first want to take some precautions?  I expect that this will break the current documentation build (the one that deploys to http://people.tuebingen.mpg.de/mpi-is-software/pam/docs/).

**Comment by vincentberenz** [comment]
> Resolved merge conflict.
> 
> @vincentberenz Can I merge or do you first want to take some precautions? I expect that this will break the current documentation build (the one that deploys to http://people.tuebingen.mpg.de/mpi-is-software/pam/docs/).

@luator  You may merge now, I "manually" update the html files for the current url

**Pull request merged**
